site_name: Кампус ИТМО в Москве
site_description: Вымышленный учебный проект – демонстрационный сайт для курсовой работы
site_author: Gunin Nikita Alekseevich
site_url: https://thegunin.github.io/devops-lab-gunin/coursework/
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  logo: images/itmo_campus_logo.png
  favicon: images/itmo_campus_logo.png
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.footer

palette:
  - scheme: default
    primary: blue
    accent: deep purple
  - scheme: slate
    primary: blue
    accent: deep purple

extra_css:
  - stylesheets/extra.css

nav:
  - Главная: index.md
  - О проекте: about.md
  - Архитектура кампуса: architecture.md
  - Технологии: technologies.md
  - Контакты: contacts.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/itmo-campus-moscow
    - icon: fontawesome/brands/telegram
      link: https://t.me/itmo_campus_moscow
    - icon: fontawesome/solid/envelope
      link: mailto:contact@itmo-campus.ru

extra_footer: >
  <div style="text-align: center; font-size: 14px; padding-top: 10px;">
    © 2025 ITMO Campus Moscow — учебный проект.<br>
    Создан в рамках курсовой работы по дисциплине «Introduction in Web Technologies».
  </div>

plugins:
  - search